// {
//     "id": 0,
//     "teacherInfo": {
//       "id": 0,
//       "fullName": "string",
//       "teacherId": "string",
//       "dateOfBirth": "2022-08-14T13:26:56.760Z",
//       "gender": "string",
//       "mobileNumber": "string",
//       "email": "string",
//       "address": "string",
//       "city": "string",
//       "postCode": "string",
//       "niNumber": "string",
//       "emergencyContact1": "string",
//       "email1": "string",
//       "number1": "string",
//       "relationship1": "string",
//       "emergencyContact2": "string",
//       "relationship2": "string",
//       "email2": "string",
//       "number2": "string",
//       "joiningDate": "2022-08-14T13:26:56.760Z",
//       "hourlyRate": 0,
//       "avgHour": 0,
//       "teacherImage": "string"
//     },
//     "selectedClass": [
//       {
//         "id": 0,
//         "teacherId": "string",
//         "yearGroup": "string",
//         "subject": "string",
//         "subSubject": "string",
//         "scheduleDay": "string",
//         "scheduleTime": "string",
//         "teacherInfo": {
//           "id": 0,
//           "fullName": "string",
//           "teacherId": "string",
//           "dateOfBirth": "2022-08-14T13:26:56.760Z",
//           "gender": "string",
//           "mobileNumber": "string",
//           "email": "string",
//           "address": "string",
//           "city": "string",
//           "postCode": "string",
//           "niNumber": "string",
//           "emergencyContact1": "string",
//           "email1": "string",
//           "number1": "string",
//           "relationship1": "string",
//           "emergencyContact2": "string",
//           "relationship2": "string",
//           "email2": "string",
//           "number2": "string",
//           "joiningDate": "2022-08-14T13:26:56.760Z",
//           "hourlyRate": 0,
//           "avgHour": 0,
//           "teacherImage": "string"
//         },
//         "teacherInfoId": 0,
//         "selectedSubjects": [
//           {
//             "id": 0,
//             "selectedClass": "string",
//             "selectedClassId": 0,
//             "studentInfo": {
//               "id": 0,
//               "studentId": "string",
//               "fullName": "string",
//               "dateOfBirth": "2022-08-14T13:26:56.760Z",
//               "gender": "string",
//               "mobileNumber": "string",
//               "email": "string",
//               "address": "string",
//               "city": "string",
//               "postCode": "string",
//               "enrolmentDate": "2022-08-14T13:26:56.760Z",
//               "year": "string",
//               "contactPerson1": "string",
//               "emailPerson1": "string",
//               "mobilePerson1": "string",
//               "contactPerson2": "string",
//               "emailPerson2": "string",
//               "mobilePerson2": "string",
//               "allergies": "string",
//               "medicalDifficulties": "string",
//               "learningDifficulties": "string",
//               "studentImage": "string"
//             },
//             "studentInfoId": 0,
//             "studentId": "string"
//           }
//         ]
//       }
//     ]
//   }